//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleMake
    {
        public VehicleMake()
        {
            this.VehicleModels = new HashSet<VehicleModel>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Abrv { get; set; }
    
        public virtual ICollection<VehicleModel> VehicleModels { get; set; }
    }
}
